### ISSUE TITLE
error with opentok secret key

### ISSUE THREAD

**Issue by ghost** [opentok/opentok-archive-transcription-demo#1]
Hi,
i am followed your all steps but every time getting this error
every time it is asking secret_key ,where i want to put secret_key in my code
you are not mentioned about secret_key please help me 
below error i am getting 
 throw new Error('Invalid arguments when initializing OpenTok: apiKey=' + apiKey + ', apiSecret=' + apiSecret);
    ^

Error: Invalid arguments when initializing OpenTok: apiKey=46223952, apiSecret=undefined
    at new OpenTok (/var/www/html/opentok_kp/opentok23/node_modules/opentok/lib/opentok.js:77:11)
    at Object.<anonymous> (/var/www/html/opentok_kp/opentok23/server.js:36:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node throw new Error('Invalid arguments when initializing OpenTok: apiKey=' + apiKey + ', apiSecret=' + apiSecret);
    ^

please give any solution
               Thank you

**Comment by MichaelJolley** [comment]
@
